### PR TITLE
Attempt to support the latest API (Work in Progress)

### PR DESCRIPTION
**Pull request by marians**
OpenWeathermap has discontinued the API version 2.1, which is the one supported by the current code in master.

This PR represents the work in progress attempt to support API version 2.5.

Feel free to comment or send your own Pull Requests based on the `api-version-2-5` branch.

### CODE REVIEW

**Comment by marians** [comment]
Currently I have trouble reconstructing the method fetching historic data for a given station ID, where start and end are given as dates (`get_historic_weather()`). The [API docs](http://openweathermap.org/api_station) don't mention the old start and end URL parameters any longer.

This URL, which is a translation from the 2.1 version to the current route, only produces error 500 for me.
http://api.openweathermap.org/data/2.5/history/station?id=136098&type=hour&start=1431625203&end=1431711603

Hard to tell if this is due to bad request parameters.

**Comment by jlmcgehee21** [comment]
Is there an eta on this?

**Comment by marians** [comment]
No, @jlmcgehee21, there is no timeline for the work on this.

**Comment by jlmcgehee21** [comment]
Oh no, I just found this project and was looking forward to using it.  I wouldn't mind contributing if it's not terribly far from being done.

**Comment by marians** [comment]
It looks as if openweathermap.org has discontinued the option to fetch historical station data for arbitrary time intervals. See http://openweathermap.org/history#stations for the current offering.

Conceptually, this means that the client should work different in the future:
- whenever station data is fetched, this is to be cached locally.
- when a time frame is queried, this has to be taken directly from "recent" data or from cache. If the time frame can't be served from either of those, the request can't be fulfilled.

So if somebody wants to create a long-term archive of weather data, it has to be done be regularly querying the openweathermap service. Since the fetched copy is, after some time, the only accessible version of the data, this puts some more strain on reliable data storing. I guess that's outside the scope of what should be handled in a client tool like this.

**Comment by marians** [comment]
Sorry, can't do any work on this due to time constraints and priorities.

**Pull request closed without merging**
